### ISSUE TITLE
not recognizing webcam from microscope

### ISSUE THREAD

**Issue by ebarry** [publiclab/infragram#10]
Hi all, 
I'm writing in to report some steps that i followed on https://infragram.org/sandbox/?webgl=true while attempting to view the webcam feed from the #communitymicroscope via infragram.org while on my Chromebook: 

* I clicked the camera button on the webpage and chose "Raw" and clicked `Begin` button.
* The screen remained black, showing no variation from turning a bright light on and off directly into the camera. 
* I also tried the other "basic" modes, with the same result. 

I am wondering if it will be possible to use infragram.org to view the microscope feeds on computers where downloading software is not feasible. 

Thank you!

**Comment by jywarren** [comment]
Hi, Liz - please try the non-webgl versino at https://infragram.org/sandbox

However, for basic microscope usage, this really is just a webcam viewer --
any standard webcam software will work, online or off. So if Infragram
doesn't work for you, you can go ahead and use whatever webcam software is
built in on your computer, or another online webcam site!

**Comment by ebarry** [comment]
Thanks! I can use the "camera" app on this Chromebook just fine, and i was surprised to discover that i also had Zoom somehow, and i could also select the camera using Zoom. Had to login with our account though.

**Comment by jywarren** [comment]
Closing this as it's for a different version of the software!
