### ISSUE TITLE
Wrong tag link to PL infragram uploads page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/infragram#109]
On home page there is this  link "browse them here"  

![Screenshot from 2020-05-14 18-19-09](https://user-images.githubusercontent.com/17081074/81952916-b430e300-960f-11ea-9e6b-aec174b6453d.png)

that links to https://publiclab.org/tag/infragram-uploads but there are no posts with that tag...but I believe the link should be https://publiclab.org/tag/infragram-upload that has posts

**Comment by cesswairimu** [comment]
Actually seems like this is the more popular tag https://publiclab.org/tag/infragram

**Comment by rimow** [comment]
hello @cesswairimu i am a first timer can I give this one a try? Thanks !

**Comment by cesswairimu** [comment]
Hi @rimow sure...go ahead..Thanks

**Comment by rimow** [comment]
hello @cesswairimu can i get a little help please ? i cloned this repo https://github.com/publiclab/infragram and searched everywhere to find the html code for the home page you mentionned but could not find it. Am I looking at the right place ? Thanks

**Comment by Tlazypanda** [comment]
Hey rimow! did some digging and the best I could find was here https://raw.githubusercontent.com/p-v-o-s/infragram-js/master/views/index.jade but then again the alert message is not visible here too maybe @cesswairimu can help out :sweat_smile:

**Comment by cesswairimu** [comment]
Thanks all..I tried checking too and I couldn't find it in this repo...not sure if we are using another source code for the live code...sorry about that
@rimow if you would like to work on another issue on any of our other repos let me know and I can find a first-timer-issue elsewhere. Thanks everyone again

**Comment by rimow** [comment]
hello thanks @Tlazypanda and @cesswairimu for checking. I could not find any other unassigned first timer issue, if you have one i would be glad to work on it.

**Comment by jywarren** [comment]
Ah, i think this is a static fix to a front page we aren't tracking in Git any more! But, I just made the change, thanks for catching it!!!
