### ISSUE TITLE
Can only select an image once

### ISSUE THREAD

**Issue by Colin-Fredericks** [publiclab/infragram#123]
Steps to replicate:
* Open https://infragram.org/sandbox/index.html on Safari, Firefox, or Chrome on MacOS
* Click under "Source" to upload an image.
* At any later point, click the upload button again to pick a new image. Nothing will happen. No message is shown to the user, and nothing is printed to the console.

If the button is not intended to function twice, it should probably be set to disabled.

**Comment by janvi01** [comment]
Hey, I would like to work on this.

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue.

**Comment by TildaDares** [comment]
Hi @ShwetKhatri2001, you can take this up.

**Comment by jywarren** [comment]
Hi, thank you for documenting this bug. I think we need to trace the path of this -- it starts with the file selection element here:

https://github.com/publiclab/infragram/blob/80f3de4ddd96c2d5b452462d74076eab73ea0376/index.html#L92-L95

That changing then triggers the `updateImage()` function from the currently selected processor (webgl is default, i believe?)

https://github.com/publiclab/infragram/blob/80f3de4ddd96c2d5b452462d74076eab73ea0376/src/ui/interface.js#L79

So if we're in webgl processor mode, we then go to `updateImage()` in there, which begins converting the image using the provided "infragrammar" expression and colormap:

https://github.com/publiclab/infragram/blob/5938a4c1a3aa834735a32cf5decacbc035668cda/src/processors/webgl.js#L220-L227

At that point we don't have to keep tracing, as it should work the same for all use cases. So I think we should add a console.log statement to see if `updateImage()` is properly getting called each time the file select element gets a new image?

**Comment by janvi01** [comment]
Hey, @jywarren I am willing to work on this issue but I am not able to produce this issue locally, the image can be uploaded several times on clicking upload image, Please if you can check on your side. Thanks!


However , the issue can be replicated as mentioned.
> Steps to replicate:
> 
> * Open https://infragram.org/sandbox/index.html on Safari, Firefox, or Chrome on MacOS
> * Click under "Source" to upload an image.
> * At any later point, click the upload button again to pick a new image. Nothing will happen. No message is shown to the user, and nothing is printed to the console.
> 
> If the button is not intended to function twice, it should probably be set to disabled.

**Comment by jywarren** [comment]
That's odd - so locally it doesn't happen but on the website it does? I
wonder if we fixed it without realizing and the website just needs to be
updated to the latest version?

**Comment by jywarren** [comment]
Hi, i realize this was fixed after all and i just republished the latest version of the code! Try it now! Thank you!!
