### ISSUE TITLE
Add a toggle-able grid overlay to the video feed

### ISSUE THREAD

**Issue by jywarren** [publiclab/infragram#14]
On the demo, we should add a button with a "ruler" icon -- that turns on a grid overlay:

https://publiclab.github.io/infragram/

![screenshot 2018-11-07 at 2 06 26 pm](https://user-images.githubusercontent.com/24359/48154358-6dce2b80-e296-11e8-93da-e5debee47915.png)

Here's the code to do this:

```html
<div style="position:absolute;width:800px;height:600px;">
  <img src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Lightblue_empty_grid.svg">
</div>
```

We'll have to make it 'unclickable' too - there's a CSS property for that... to let clicks pass through to the layer below...

We can insert it into the `index.html` file

**Comment by jywarren** [comment]
Above this line! 

https://github.com/publiclab/infragram/blob/7b0567b46b0a80f41e962bb1b5a78cc9d0b4853a/index.html#L162

Let's use the fontawesome icon class `fa fa-grid` for now!

**Comment by mrtmrtmlck** [comment]
Hi! I would like to pick this issue 😊

**Comment by jywarren** [comment]
Oh wow, that would be great!

**Comment by jywarren** [comment]
Follow-up ideas: 

* [ ] add a slider which changes the size of the grid by changing the `<img>` tag's width parameter. 
* [ ] have a button which lets you "save" the size using `localStorage`. 
* [ ] have it include metadata when it exports the image into Image Sequencer!

**Comment by mrtmrtmlck** [comment]
> Follow-up ideas:
> 
> * [ ]  add a slider which changes the size of the grid by changing the `<img>` tag's width parameter.
> * [ ]  have a button which lets you "save" the size using `localStorage`.
> * [ ]  have it include metadata when it exports the image into Image Sequencer!

Thanks for your guidance! I will work on this asap.

**Comment by jywarren** [comment]
ah, you don't have to do all these at once -- sorry! i'm just excited about
next steps after this first one. Let's do it one at a time! Thank you!

**Comment by mrtmrtmlck** [comment]
@jywarren Hi! I could find time yet for this issue. Could you please help me about how to run the application ? I cloned the repo and npm install but npm start or node Infragram.js commands do not work.

**Comment by jywarren** [comment]
ah, ok -- what is your output from the commands? Can you paste it into a
https://gist.github.com?

**Comment by mrtmrtmlck** [comment]
sure, here it is:
https://gist.github.com/mrtmrtmlck/3c70d199f473f5ed964e159d13ce7d1c

**Comment by jywarren** [comment]
Oh, interesting... i see! You can actually run this only in the browser at the moment; perhaps the package.json file is misconfigured for `npm start` -- let me see.

can you try running it with `grunt serve`? 

I'll try to set up a better `npm start` script, though. Good call.

**Comment by mrtmrtmlck** [comment]
> OK, sorry - not `grunt serve` but this should work: `npm install http-server -g && http-server` (this installs it and runs it, next time just `http-server` will work)

Thanks a lot! You may review my pull request

**Comment by jywarren** [comment]
The initial step is now live! https://publiclab.github.io/infragram/

**Comment by jywarren** [comment]
@MargaretAN9 - based on your work, take a look! A few steps to go to make it fully functional for scaling 👍 🎉

**Comment by jywarren** [comment]
Oh awesome. the last one will be a follow-up issue we could break out. 

I don't see all of them at https://github.com/publiclab/infragram/pull/19 -- did you push up additional commits somewhere else? Thanks so much!!!

**Comment by mrtmrtmlck** [comment]
> Oh awesome. the last one will be a follow-up issue we could break out.
> 
> I don't see all of them at #19 -- did you push up additional commits somewhere else? Thanks so much!!!

It was a pleasure! Actually, they're all in that commit. Which one don't you see ?

**Comment by jywarren** [comment]
Hi, just checking on this - i don't see that the cells of the grid are square in the latest version. Is there a fix we might need to make?

![image](https://user-images.githubusercontent.com/24359/50934072-76c5af80-1435-11e9-9371-f188289ddd9c.png)

**Comment by jywarren** [comment]
I also noticed that the grid is expanding/contracting in only one dimension. Can we update it to adjust in 2 dimensions? Thank you!! 

![infragram](https://user-images.githubusercontent.com/24359/50937079-4a636080-1440-11e9-98b7-9092d0fa44dd.gif)

**Comment by mrtmrtmlck** [comment]
@jywarren I will check and inform you 👍

**Comment by jywarren** [comment]
amazing. Many thanks.

**Comment by jywarren** [comment]
I've started an attempted fix here but didn't make a lot of progress. But I hope this is helpful! https://github.com/publiclab/infragram/pull/56

**Comment by jywarren** [comment]
OK, I think I got this working here: https://github.com/publiclab/infragram/pull/76

**Comment by jywarren** [comment]
And updated at https://publiclab.org/notes/MaggPi/06-23-2018/microscope-calibration-overlays-what-s-the-best-approach
