### ISSUE TITLE
see here

### ISSUE THREAD

**Issue by gptshubham595** [publiclab/infragram#16]
https://github.com/publiclab/infragram/blob/7b0567b46b0a80f41e962bb1b5a78cc9d0b4853a/index.html#L162

**Comment by gauravano** [comment]
@gptshubham595 please update the issue. Thanks!

**Comment by gauravano** [comment]
Hi @gptshubham595 I have to close this one due to inactivity from long duration and incomplete details. If you want to reopen this and add more details, feel free to do so. Thanks!
