### ISSUE TITLE
Broken Link in Infragram title

### ISSUE THREAD

**Issue by madhhuurrii** [publiclab/infragram#187]
On clicking the below title it redirects to a 404 page.
![image](https://user-images.githubusercontent.com/64744084/155935329-c50a798b-5d06-466a-ad45-424658e76964.png)

Possible Solution:
In the footer section, Infragram redirects to the following link: https://publiclab.org/wiki/infragram

**Comment by TildaDares** [comment]
Hi @madhhuurrii, thanks for catching this. Are you interested in working on this?

**Comment by madhhuurrii** [comment]
Yes!
