### ISSUE TITLE
Padding left of container is unset

### ISSUE THREAD

**Issue by Syed-Ansar** [publiclab/infragram#188]
Padding to the left is unset i.e., 0

![Mobile View](https://user-images.githubusercontent.com/82027712/155968428-a6f57675-019f-4703-9aaf-22b2e0cc6c9f.jpeg)

Solution is : Container padding should be removed.

<img width="1440" alt="Screenshot 2022-02-28 at 4 12 08 PM" src="https://user-images.githubusercontent.com/82027712/155969343-852b1944-6931-4895-9b4b-2bd360a8feaa.png">

**Comment by Syed-Ansar** [comment]
I am working on this issue.

**Comment by TildaDares** [comment]
@Syed-Ansar Sure

**Comment by Syed-Ansar** [comment]
Thank you @TildaDares
