### ISSUE TITLE
Unable to hover over COLORIZE dropdown items

### ISSUE THREAD

**Issue by AbihaFatima** [publiclab/infragram#192]
While trying to select the colorize dropdown items, the mouse cursor fails to hover over ‘Default colormap’ and ‘Stretched colormap’.
![GIF](https://user-images.githubusercontent.com/70844041/156249123-77946611-8123-43c7-8c5f-f6077ba8e75c.gif)

**Comment by AbihaFatima** [comment]
@TildaDares 
Can I work on this?

**Comment by TildaDares** [comment]
Sure @AbihaFatima
