### ISSUE TITLE
Favicon is not linked

### ISSUE THREAD

**Issue by madhhuurrii** [publiclab/infragram#193]
While running the website, I came across this error

![image](https://user-images.githubusercontent.com/64744084/156301597-df1b39a2-58dc-4b35-bacc-9d41eaba40bc.png)
Though the favicon is present in the assets folder it is not linked to the page.

Solution:
link the favicon to the page.

**Comment by Syed-Ansar** [comment]
Can I work on this ?

**Comment by TildaDares** [comment]
Hi @madhhuurrii, is this issue available for @Syed-Ansar to work on?

**Comment by madhhuurrii** [comment]
Yes,Sure!

**Comment by TildaDares** [comment]
Hi @Syed-Ansar, you can work on this.

**Comment by Syed-Ansar** [comment]
> Hi @Syed-Ansar, you can work on this.

Okay @TildaDares I will work on this. Thank you.
