### ISSUE TITLE
Old code to document and/or deprecate/remove

### ISSUE THREAD

**Issue by jywarren** [publiclab/infragram#212]
Let's talk through these possible areas to trim code. Once we agree on it, we can break out separate issues for each.

- [x] Socket upload: We used to send the image up to a Python server [using sockets](https://github.com/publiclab/infragram/blob/80f3de4ddd96c2d5b452462d74076eab73ea0376/src/file-upload.js#L54-L66). This code can be removed. Done in https://github.com/publiclab/infragram/pull/214
- [x] we can also remove the "thumbnail generation" code here since that's now handled by PublicLab.org : https://github.com/publiclab/infragram/blob/80f3de4ddd96c2d5b452462d74076eab73ea0376/src/file-upload.js#L26-L45

We also don't use the javascript code any more in production. Read more about it in the README but I'm not confident it all works?

**Comment by shubhangi013** [comment]
Hey! I went through the code. Could you elaborate on how is the org handling the thumbnail? I am afraid I couldn't figure it out despite going through the repository and rummaging through the documentation :sweat_smile: 
I did find the file and function saving the uploaded thumbnail.
This looks interesting and I would like to work on it.

**Comment by jywarren** [comment]
Hi, so, before, we would generate a thumbnail using this, and upload it. But now we don't do that, and this code isn't called from anywhere. I think you can simply delete everything highlighted above!

But if you want to be sure you could search the codebase for instances of `uploadThumbnail`. Thank you!!

**Comment by shubhangi013** [comment]
> Hi, so, before, we would generate a thumbnail using this, and upload it. But now we don't do that, and this code isn't called from anywhere. I think you can simply delete everything highlighted above!
> 
> But if you want to be sure you could search the codebase for instances of `uploadThumbnail`. Thank you!!

Cool! I'd love to work on this issue.

**Comment by shubhangi013** [comment]
I guess the file doesn't exist on the main branch :sweat_smile: 
should I compare my changes with another branch?
@jywarren

**Comment by jywarren** [comment]
I just searched in GitHub for contents inside of files -- and found one:

https://github.com/publiclab/infragram/search?q=uploadThumbnail

It's used in this block of code:

https://github.com/publiclab/infragram/blob/f15add6ae6057bd99b4b1b930449f75ca974270e/src/ui/saving.js#L10-L34

However, I suspect that we don't use that either. It is initialized here:

https://github.com/publiclab/infragram/blob/c572263ae8ba63f3beb64dc193f363d182e8a838/src/ui/interface.js#L43

But, we just don't have any button with an id of `save` -- so it never gets activated. I think in an old version of the code we did. But now, `index.html` has these save options, and none have an id of "save":

https://github.com/publiclab/infragram/blob/24bcd298405be8aa65274a50cb54c5b317d4c606/index.html#L168-L173

So, i think we can delete the original code, as well as `/src/ui/saving.js` and line 43 of `/ui/interface.js`. All three would need to be done in the same pull request. Want to try?

**Comment by shubhangi013** [comment]
Yes I'll get started! Thankyou for explaining!

**Comment by Somya-Singhal** [comment]
If this issue is still open or any help is needed, can I collaborate with you @shubhangi013 ?

**Comment by jywarren** [comment]
Hi @shubhangi013 i see this is now complete, so I'm closing this! Thank you!!

@Somya-Singhal i'm sorry this was already solved. I'm hoping to open some additional opportunities for contribution if I have time today! Thank you!

**Comment by Somya-Singhal** [comment]
Sure @jywarren, I would be happy to work on fixing those issues.
