### ISSUE TITLE
Copy in our improved First-Timers-Only template from the plots2 repository

### ISSUE THREAD

**Issue by jywarren** [publiclab/infragram#227]
Our customized workflow for the first-timers bot is a little different from the default, so we need to copy in our custom template (see example here of the default: https://github.com/publiclab/infragram/issues/224 vs. the custom one here: https://github.com/publiclab/plots2/issues/10784)

Here's the template:

https://github.com/publiclab/plots2/blob/main/.github/first-timers-issue-template.md

We'd love help copying it to the corresponding location in this repository!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by Ash-KODES** [comment]
I am taking this issue:)

**Comment by jywarren** [comment]
Yes please, we'd love that!
