### ISSUE TITLE
HSV mode doesn't work in default mode (webgl)

### ISSUE THREAD

**Issue by jywarren** [publiclab/infragram#261]
Switching the Convert/Analyze menu to HSV mode doesn't work; this is because we only have an HSV handler for javascript processing mode, not webgl, and our default startup mode is webgl. 

The mode runs this function:

`options.processor.save_expressions_hsv`

And as you can see, in the JavaScript mode we have that just below the "regular" `save_expressions` function:

https://github.com/publiclab/infragram/blob/f15add6ae6057bd99b4b1b930449f75ca974270e/src/processors/javascript.js#L160-L188

But we don't have the equivalent for webgl, because webgl is a lot more complex and we never finished replicating that:

https://github.com/publiclab/infragram/blob/f15add6ae6057bd99b4b1b930449f75ca974270e/src/processors/webgl.js#L268

I'm not sure how hard it would be to write a webgl version; the converters at https://github.com/publiclab/infragram/blob/f15add6ae6057bd99b4b1b930449f75ca974270e/src/color/converters.js would have to be adapted, or we'd have to figure out how to calculate HSV model color in WebGL code. 

We don't use the Javascript processor any more... it's permanently set to WebGL:

https://github.com/publiclab/infragram/blob/fac812fbd97c8ef8eec021d7aaab29b799bb0ed3/index.html#L231

So i think for now the quick fix is to comment out the HSV option, sadly!

https://github.com/publiclab/infragram/blob/fac812fbd97c8ef8eec021d7aaab29b799bb0ed3/index.html#L113

**Comment by wisdomekpotu** [comment]
@jywarren can i go ahead and submit a PR

**Comment by wisdomekpotu** [comment]
@jywarren i have made a PR for this here https://github.com/publiclab/infragram/pull/263 Plz review

**Comment by jywarren** [comment]
thank you!! solved in https://github.com/publiclab/infragram/pull/263
