### ISSUE TITLE
Beautifying the README.md for infragram 

### ISSUE THREAD

**Issue by girija0707** [publiclab/infragram#264]
At present the following two lines, **let the code be with you and happy open sourcing** don't go with the structure of readme.md

![b9cda5e0-b6b3-4427-976b-dac479be67da](https://user-images.githubusercontent.com/63583646/160771584-79404420-01da-446f-b24f-aecba3b713db.jpg)

Would love to make a slight change in the lines to maintain the uniformity of the readme

![b5a50674-6844-494b-96c2-3865dfe3f785](https://user-images.githubusercontent.com/63583646/160771655-daf07c37-4575-407e-b415-0848a493dd12.jpg)

**Comment by girija0707** [comment]
do let me know if I can go ahead with this and work on it @TildaDares  @jywarren

**Comment by 17neelam** [comment]
@TildaDares @jywarren 
I am Neelam. I will like to work on this issue.

**Comment by girija0707** [comment]
Hey @TildaDares can I go ahead with this

**Comment by jywarren** [comment]
Hi @girija0707 this looks like a nice contribution to make, either yourself if it's your first time, or if you have made a contribution already, you could try creating a "first-timers-only" issue for someone else! I'll leave some information about that below:

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by girija0707** [comment]
> Hi @girija0707 this looks like a nice contribution to make, either yourself if it's your first time, or if you have made a contribution already, you could try creating a "first-timers-only" issue for someone else! I'll leave some information about that below:
> 
> This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

It's great if this can be made into a FTO , since I've completed mine a few days ago I would love newbies working on it 😄

**Comment by jywarren** [comment]
Hi, @girija0707 since you've completed yours, would you be interested in trying to create an FTO from this for someone else, if it hasn't yet been solved? Thanks!!!

**Comment by girija0707** [comment]
> Hi, @girija0707 since you've completed yours, would you be interested in trying to create an FTO from this for someone else, if it hasn't yet been solved? Thanks!!!

Hello @jywarren yes, I created an FTO out of it and I believe @TildaDares assigned it to a newbie too😊

**Comment by 7malikk** [comment]
Hello, @TildaDares Can i handle this as it is still open?

**Comment by TildaDares** [comment]
Hi @7malikk, the README has been updated and no longer uses the formatting in the screenshot above. I think we can close this now as it has been resolved. Thank you!
