### ISSUE TITLE
Images in readme should be center aligned 

### ISSUE THREAD

**Issue by shubhangi013** [publiclab/infragram#265]
the images are by default left-aligned. They should be center-aligned.

**Comment by kunmi02** [comment]
@TildaDares 

I will like to work on this issue

**Comment by shubhangi013** [comment]
> @TildaDares 
> 
> I will like to work on this issue

Hey! I've already opened a PR regarding this.

**Comment by 17neelam** [comment]
hello!
I am Neelam from IIT Roorkee . I will like to work on this issue.

**Comment by 17neelam** [comment]
@TildaDares 
hello!
I am Neelam from IIT Roorkee . I will like to work on this issue.

**Comment by shubhangi013** [comment]
Closing this via #266
