### ISSUE TITLE
Change typo error ('ru') on line 176 to 'run' in the README.md file.

### ISSUE THREAD

**Issue by akanbifatimah** [publiclab/infragram#278]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted)[](https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md#-what-you-will-need-to-know)[](https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md#-step-by-step) issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
 🙋 Claim this issue: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
💡 Learn how to claim 🙋
 📝 Update the file [README.md](https://github.com/publiclab/infragram) in  (https://github.com/publiclab/infragram/blob/main/README.md) repository (press the little pen Icon) and edit the line as shown below.
[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a -) which lines to remove, and in green (and a +) which lines to add:

```diff 
@@ -173,7 +173,7 @@ 
 

-a Similarly, we can "send" the image to https://sequencer.publiclab.org, as a data-url although it may fail for very large images since we must [send it in a GET request](https://github.com/publiclab/infragram/blob/34d330001e3869da9caf34cb79d6dc7650c1db83/index.html#L250-L254). It is then ru through a similar (but not identical, unfortunately) set of steps of conversion and colorizing, in the step-by-step interface of Image Sequencer, for fine-tuning. Learn more about this technique here: https://publiclab.org/notes/warren/08-02-2018/use-image-sequencer-for-ndvi-plant-analysis-with-a-modified-mini-sport-camera
+b Similarly, we can "send" the image to https://sequencer.publiclab.org, as a data-url although it may fail for very large images since we must [send it in a GET request](https://github.com/publiclab/infragram/blob/34d330001e3869da9caf34cb79d6dc7650c1db83/index.html#L250-L254). It is then run through a similar (but not identical, unfortunately) set of steps of conversion and colorizing, in the step-by-step interface of Image Sequencer, for fine-tuning. Learn more about this technique here: https://publiclab.org/notes/warren/08-02-2018/use-image-sequencer-for-ndvi-plant-analysis-with-a-modified-mini-sport-camera
:
```

 💾 Commit your changes

 🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.

If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)[](https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md#please-keep-us-updated)[](https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md#is-someone-else-already-working-on-this) and open a pull request from there.

 🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all)[](https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md#-questions). Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by VictoriaAjala** [comment]
Can I work on this issue?

**Comment by akanbifatimah** [comment]
Hi @VictoriaAjala , Please hold on , @TildaDares would have to review this issue to kno if its fit for a first time only issue

**Comment by TildaDares** [comment]
Hi @akanbifatimah, great catch but this issue has been resolved in #247. You can view the [updated README](https://github.com/publiclab/infragram#export-to-image-sequencer) now.

**Comment by akanbifatimah** [comment]
@TildaDares,oh I didn't see that earlier. Thank you for pointing it out. I will close this issue now

**Comment by VictoriaAjala** [comment]
Thanks @TildaDares for the update, I'd look around for other open issues while waiting for you to assign me one. 🙂
