### ISSUE TITLE
Update CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by TildaDares** [publiclab/infragram#285]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [CODE_OF_CONDUCT.md](https://github.com/publiclab/infragram/blob/main/CODE_OF_CONDUCT.md) in the `Infragram` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,4 +1,7 @@
-﻿Public Lab, 55 Cromwell Street, 1C, Providence, RI 02907
+﻿# Public Lab Code of Conduct 
+
+_Public Lab, 55 Cromwell Street, 1C, Providence, RI 02907_
+
 We are coming together with an intent to care for ourselves and one another as we produce knowledge in pursuit of environmental justice. For this to work for everybody, individual decisions will not be allowed to run counter to the welfare of other people. We—visitors, community members, community moderators, staff, organizers, sponsors, and all others—hold ourselves accountable to the same values regardless of position or experience. This community aspires to be a respectful place both during online and in-person interactions so that all people are able to fully participate with their dignity intact. This document is a piece of the culture we're creating.
 
 This code of conduct applies to all spaces managed by the Public Lab community and non-profit, both online and in person. It provides a clear set of practical guidelines for events led by organizers and community members, multi-day events such as Barnraisings, and online venues such as the website, comment threads on software platforms, chatrooms, our mailing lists, the issue tracker, and any other forums created by Public Lab which the community uses for communication. For interactions with additional groups, see our Partnership Guidelines at https://publiclab.org/partners.
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Reserved for @Prakashh21 for 24 hours!

**Comment by 17neelam** [comment]
hi!   @TildaDares
I like to work on this issue. can u assign me this issue?

**Comment by FonyaBrandone** [comment]
Hello Mrs @TildaDares, I am an outreachy applicant and would like to work on the UI Redesign project with great Design features. For the mean time I would like to contribute to this open issue if possible. Thanks!

**Comment by TildaDares** [comment]
Hi @17neelam, go ahead! Thanks.

**Comment by TildaDares** [comment]
Hi @17neelam, do you need help with this?

**Comment by 17neelam** [comment]
> Hi @17neelam, do you need help with this?

yes @TildaDares  I am not able to understand how to initiate.

**Comment by TildaDares** [comment]
Hi @17neelam, have you gone through the guide on how to contribute in the description above?

**Comment by 17neelam** [comment]
> Hi @17neelam, have you gone through the guide on how to contribute in the description above?

yes i did that but not getting the code file on which i have to work.

**Comment by TildaDares** [comment]
@17neelam This is the file https://github.com/publiclab/infragram/blob/main/CODE_OF_CONDUCT.md

**Comment by 17neelam** [comment]
@TildaDares can you please tell me in short what I have to do in this issue. please help me to understand the issue.

**Comment by TildaDares** [comment]
@17neelam You need to go to https://github.com/publiclab/infragram/blob/main/CODE_OF_CONDUCT.md and then follow the instructions in this article https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files.

The lines in red should be deleted and the ones in green added.

**Comment by 17neelam** [comment]
@TildaDares  after doing the changes. How I Creating a commit with multiple co-authors. from where I find required co-author information.
help me in this pleases.

**Comment by 17neelam** [comment]
@TildaDares  in creating the commit with authors do have to mention only you or there are other authors too?

**Comment by TildaDares** [comment]
@17neelam You're the only author that should be added. No one else.

**Comment by 17neelam** [comment]
@TildaDares  what I have to do after creating the pull request?

**Comment by 17neelam** [comment]
@TildaDares  as this is my first time working in open source i don't know if I going right or not. please correct me if I am getting wrong.
Thank you

**Comment by TildaDares** [comment]
@17neelam I've merged the pull request. Thanks for working on this!!

**Comment by 17neelam** [comment]
@TildaDares what do I have to do next?

**Comment by TildaDares** [comment]
Hi @17neelam, you can open a first-timers only issue for someone else or work on issues with the `bug` or `help wanted` labels. Thanks!

**Comment by 17neelam** [comment]
@TildaDares  do I have to create a proposal? is it necessary for all?

**Comment by 17neelam** [comment]
@TildaDares in the date of contribution started I have to write the date when the issue is assigned to me or when I start working?

**Comment by TildaDares** [comment]
Hi @17neelam, you can add the day you were assigned the issue.
