### ISSUE TITLE
Cleaning of unecessary logs

### ISSUE THREAD

**Issue by shubhangi013** [publiclab/infragram#289]
There are a lot of very unnecessary logs throughout the code. For example : 

https://github.com/publiclab/infragram/blob/ed49410ea322a4e09f0b670efa5d606a0f9cf57b/dist/infragram.js#L487

and 
https://github.com/publiclab/infragram/blob/ed49410ea322a4e09f0b670efa5d606a0f9cf57b/dist/infragram.js#L1497

Can we remove these? there are other helpful ones that actually help the developers while contributing to the code like:
https://github.com/publiclab/infragram/blob/ed49410ea322a4e09f0b670efa5d606a0f9cf57b/dist/infragram.js#L113

however, as pointed out above, there are some unnecessary and vague ones too. I would like to work and remove/ rephrase these.

**Comment by TildaDares** [comment]
Hi @shubhangi013, go ahead. Thanks!

**Comment by govindgoel** [comment]
@shubhangi013 yeah, you can remove the redundant logs and maybe comment out those which might help in debugging sometime.

**Comment by shubhangi013** [comment]
> @shubhangi013 yeah, you can remove the redundant logs and maybe comment out those which might help in debugging something.

Right! Thankyou 😊

**Comment by TildaDares** [comment]
Resolved in #293
