### ISSUE TITLE
"Show less" option in Q&A section not functioning 

### ISSUE THREAD

**Issue by sarxxt** [publiclab/infragram#295]
![Screenshot (98)](https://user-images.githubusercontent.com/83841462/161062036-ee9eab09-cf80-420b-b455-1f6271893ad2.png)

**Comment by ShrutiKoli19** [comment]
Hi, I would like to work on this issue.

**Comment by TildaDares** [comment]
Hi @sarxxt, thank you for opening this. This issue is a problem with the plots2 repo and not Infragram. We have an issue open to resolve this in https://github.com/publiclab/plots2/issues/10817. Thanks!

**Comment by sarxxt** [comment]
hi @TildaDares can you mark this issue as proposal?

**Comment by TildaDares** [comment]
Infragram embedded a plots2 iframe in its own site. You were not on the wrong page.

**Comment by sarxxt** [comment]
Hi @TildaDares, I am an outreachy applicant.  Since the Infragram project is not accepting pull requests due to outreachy project, could you tell me how can we submit our contributions then?

**Comment by FonyaBrandone** [comment]
Hello Mrs @TildaDares, I am an outreachy applicant and am excited about open source and contributing. Please I would like to know how to go about the contributions. Thank You!
