### ISSUE TITLE
URL.createObjectURL with media streams is deprecated and will be removed around July 2018

### ISSUE THREAD

**Issue by jywarren** [publiclab/infragram#3]
infragram.js? [sm]:831 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

https://www.chromestatus.com/features/5618491470118912

**Comment by Somya-Singhal** [comment]
Is this issue still there? Because I had seen the files and not found where it's been used😅.

**Comment by jywarren** [comment]
Thank you, i believe this is long fixed, apologies!!!
