### ISSUE TITLE
Empty ruleset

### ISSUE THREAD

**Issue by girija0707** [publiclab/infragram#307]
The  style attribute is empty is it fine to remove it
 ![Screenshot (84)](https://user-images.githubusercontent.com/63583646/161384133-8a826092-01c2-4057-ad59-b974667f4ca1.png)
 
```diff
-          <div class="zone last" id="save-zone" style=" ">
+          <div class="zone last" id="save-zone">
```

**Comment by girija0707** [comment]
@TildaDares is it fine to remove this style attribute as it is empty

**Comment by TildaDares** [comment]
Hi @girija0707, yes go ahead

**Comment by girija0707** [comment]
Su

> Hi @girija0707, yes go ahead
Thank you 😊

**Comment by girija0707** [comment]
hey @TildaDares  there was some mess while trying to create pull request hence I had to delete my fork repository  and again fork and clone the repository but now I don't see this error in the code that I had seen earlier

**Comment by girija0707** [comment]
would you please review the issue I had opened earlier regarding readme.md file #264

**Comment by jywarren** [comment]
No problem @girija0707 thank you for your help here!
