### ISSUE TITLE
Empty paragraph tag in index.html

### ISSUE THREAD

**Issue by girija0707** [publiclab/infragram#314]
The paragraph tag is empty and hence can also be removed
![Screenshot_2022-04-04-00-54-20-33_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/63583646/161444830-e74c57e3-a2b5-45e3-98f6-5b22cb6ca2aa.jpg)

**Comment by girija0707** [comment]
@TildaDares would like to remove it to make make the code cleaner

**Comment by TildaDares** [comment]
Hi @girija0707, go ahead! Thanks

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by TildaDares** [comment]
Hi @girija0707, would you like to make a first-timers issue from this? I can help with that if you're interested.

**Comment by girija0707** [comment]
> Hi @girija0707, would you like to make a first-timers issue from this? I can help with that if you're interested.

yes @TildaDares ,would love to do that, will you please help with the template

**Comment by TildaDares** [comment]
@girija0707 All you have to do is find the New Issue button and click it. After clicking you’ll find FTO template,

**Comment by girija0707** [comment]
> @girija0707 All you have to do is find the New Issue button and click it. After clicking you’ll find FTO template.

Ok thank you

**Comment by sainamercy** [comment]
@TildaDares I've checked the file regarding this issue and there's one empty "p" tag. Can I create a first-timer-issue out of this

**Comment by TildaDares** [comment]
Hi @sainamercy, yes you can. Thank you!

**Comment by abhayvershwal** [comment]
@jywarren @TildaDares This issue can be closed as it is already resolved in https://github.com/publiclab/infragram/pull/477

**Comment by abhayvershwal** [comment]
Duplicate issue: https://github.com/publiclab/infragram/issues/474

**Comment by TildaDares** [comment]
Thank you @abhayvershwal. Closing now!
