### ISSUE TITLE
Theme Color of Tooltip

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [publiclab/infragram#317]
When we click on the image upload button and on camera button tool tip appears black whereas when we click on the colorize button the todown menu display in white theme.I would like to fix it.
![tooltip](https://user-images.githubusercontent.com/89297894/161504528-e265648b-e7b4-4766-b75b-cad9f7a703e8.png)
![WhatsApp Image 2022-04-04 at 1 23 22 PM](https://user-images.githubusercontent.com/89297894/161504586-bfb8264d-1fa9-4710-8871-aa0f8f0aa901.jpeg)
I want to chnage the theme color of tool tip same like which is display in the given below image.
![WhatsApp Image 2022-04-04 at 1 28 07 PM](https://user-images.githubusercontent.com/89297894/161504902-e1a4b1a0-9ccd-467a-a401-37f6f111bb9a.jpeg)

**Comment by jywarren** [comment]
Hi @AsmaIbrahimButt it's a very good observation, however, the two types of popups have different functions. One is called a "tooltip" and is described at https://getbootstrap.com/docs/4.6/components/tooltips/

The white one is a dropdown and described at https://getbootstrap.com/docs/4.6/components/dropdowns/

Does that make sense? Thanks!

**Comment by AsmaIbrahimButt** [comment]
@jywarren Yeah, I got it. Tool tip serve a different function whereas dropdown menu has different therefore, to recognized the functionality so that user would not confused.Thanks for sharing.

**Comment by jywarren** [comment]
OK thank you @AsmaIbrahimButt I will close this now, then. Happy to discuss more issues too! Thanks!
