### ISSUE TITLE
collapsible table of contents bar to make navigation easier

### ISSUE THREAD

**Issue by shubhangi013** [publiclab/infragram#318]
To enhance both user and developer experience, we can have a collapsible table of contents that can make navigating through the various headings easier.

one can take reference from: https://github.com/othneildrew/Best-README-Template
This is a beginner-friendly issue. You'd need to know a bit about the syntax followed by GitHub.
one can read about it here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by shubhangi013** [comment]
> @shubhangi013 Is the collapsible menu meant for Infragram or the README. If it's for Infragram, where would the menu be and what content would it contain? Thanks!

It is for the Readme

**Comment by shubhangi013** [comment]
Oh, I meant it in a sense that we can have a table of contents fro the readme with headings like 'Contributing' and 'First time?' so that it's easier for developers and users to navigate through the instructions of the readme. Just like the reference I've linked. It has a table of contents.

**Comment by TildaDares** [comment]
Is this the Table of Contents you're talking about?

<img width="404" alt="Screenshot 2022-04-04 at 15 14 36" src="https://user-images.githubusercontent.com/63427719/161563190-ec24e41b-a2a2-4ef7-b2e0-936cbe360379.png">

**Comment by shubhangi013** [comment]
Yes!

https://user-images.githubusercontent.com/78342516/161563391-8e5bd3f4-b891-4d30-8b11-6f881557b2c4.mp4

It makes it easy to navigate

**Comment by TildaDares** [comment]
I like where the idea is coming from but wouldn't a second Table of Contents be redundant. Also Github's ToC is easier to navigate because the user will always see it as they scroll.

**Comment by TildaDares** [comment]
On second thought @shubhangi013, I think we can add one. I checked other Public Lab repos and they have a second Table of Contents. If you want, you can reopen this and create an FTO for it.

**Comment by TildaDares** [comment]
But instead of the ToC being a dropdown, can it be like the one in the plots2 repo? https://github.com/publiclab/plots2#table-of-contents

**Comment by shubhangi013** [comment]
Yes it would be better. GitHub already has a collapsible one. I will reopen this!

**Comment by shubhangi013** [comment]
Thankyou! :heart:

**Comment by jywarren** [comment]
Hi @shubhangi013 thank you for the ideas!

If we make a copy of the existing first-timers issue template (for the bot) which is at https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md

And we put it in the corresponding folder as we have in the plots2 repository: https://github.com/publiclab/plots2/tree/main/.github/ISSUE_TEMPLATE/

We should be able to use it as a template here. It's a really good idea. 

Note that the version in the `ISSUE_TEMPLATE` folder has some extra material at the top - both a table, and a short explanation on how to customize the template:

```
---
name: "\U00002728 First Timers Only issue"
about: Open a First Timers Only issue for someone
title: ''
labels: fto-candidate
assignees: ''

---

### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****
```

We'd have to copy that in as well. Would you be interested in opening a pull request for that?

**Comment by jywarren** [comment]
Also for background, the TOC at plots2 was created before GitHub added the TOC feature. But i'm not strongly for or against adding another TOC!

**Comment by shubhangi013** [comment]
> Hi @shubhangi013 thank you for the ideas!
> 
> If we make a copy of the existing first-timers issue template (for the bot) which is at https://github.com/publiclab/infragram/blob/main/.github/first-timers-issue-template.md
> 
> And we put it in the corresponding folder as we have in the plots2 repository: https://github.com/publiclab/plots2/tree/main/.github/ISSUE_TEMPLATE/
> 
> We should be able to use it as a template here. It's a really good idea. 
> 
> Note that the version in the `ISSUE_TEMPLATE` folder has some extra material at the top - both a table, and a short explanation on how to customize the template:
> 
> ```
> ---
> name: "\U00002728 First Timers Only issue"
> about: Open a First Timers Only issue for someone
> title: ''
> labels: fto-candidate
> assignees: ''
> 
> ---
> 
> ### 💡Format this Issue Into a First Timers Issue
> This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!
> 
> ****
> ```
> 
> We'd have to copy that in as well. Would you be interested in opening a pull request for that?

Yeah, I'd love to! Thanks!
