### ISSUE TITLE
Removing style.styl file

### ISSUE THREAD

**Issue by ankittt20** [publiclab/infragram#332]
![Screenshot (106)](https://user-images.githubusercontent.com/92395053/162106832-46b0b6c8-c49c-48ac-a4a3-bee7a37fef22.png)
Deleting this file to make the code better.

**Comment by ankittt20** [comment]
Hey @TildaDares can I work on this issue?

**Comment by TildaDares** [comment]
@ankittt20 Go ahead! Thanks
