### ISSUE TITLE
Delete urlParams.js

### ISSUE THREAD

**Issue by ankittt20** [publiclab/infragram#348]
![Screenshot (108)](https://user-images.githubusercontent.com/92395053/162606280-4ed3090f-0055-485c-9376-d2063dbaa466.png)
Delete this file with no code to make the overall code better.

**Comment by ankittt20** [comment]
Hey @TildaDares can I work on this?

**Comment by TildaDares** [comment]
Hi @ankittt20, go ahead. Thanks!
