### ISSUE TITLE
Correcting deprecated initMouseEvent

### ISSUE THREAD

**Issue by girija0707** [publiclab/infragram#351]
The initMouseEvent in file.js is a deprecated one
![Screenshot (88)](https://user-images.githubusercontent.com/63583646/162615721-a1c4ae03-09f8-4623-bfb2-20d5800637c1.png)

Suggested changes
```diff
-      event = document.createEvent("MouseEvents");
-      event.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
-      lnk.dispatchEvent(event);
+      mouseEvent=getMouseEvent();
+      lnk.dispatchEvent(mouseEvent("click", {
+        screenX: 0,
+        screenY: 0,
+        clientX: 0,
+        clientY: 0,
+        } ) );
```

**Comment by girija0707** [comment]
@TildaDares if the suggested changes are correct I would like to work on it

**Comment by TildaDares** [comment]
Hi @girija0707, this issue is a duplicate of #315. Thanks!

**Comment by girija0707** [comment]
> Hi @girija0707, this issue is a duplicate of #315. Thanks!

Oh my bad 😅I'll close this issue
