### ISSUE TITLE
Weekly Community Check-In #137 - Call for GSoC Proposals!

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/infragram#354]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Thank Yous
Thank you all for all the help you have been offering each other. It one of the things that are special about of the PublicLab Code community : the support, collaboration and everyone willingness to help :1st_place_medal: . This tradition is extended to new contributors who in turn extend it to new contributors which is just so lovely :100: :100: .  Thanks all :heart: :heart: 

## Call for Google Summer of Code (GSoC) Proposals 

We have opened a call for the Google Summer of Code proposals on the PublicLab website [here](https://publiclab.org/notes/cess/04-11-2022/call-for-proposals-google-summer-of-code-2022). We ask applicants to post their proposal on the PublicLab website first for feedback from mentors and the community at large, which they can incorporate in their final draft that they post on the GSoC website.
Please post as soon as you can, you could even post a draft and be editing it as some parts are being reviewed(_but please indicate at the top its  an in-progress post for accurate feedback_). We are a little overwhelmed this round, so kindly post as soon as you can.
 I would like to thank everyone for all the help you are giving each other , you are all doing an awesome job and we are glad to have you all  in the community :heart: :heart: :heart: . Feel free to share below what you are working on, any questions or ask for help if stuck. 
**Remember the deadline for submitting the proposal on the GSoC webite is on April 19, 2022.**
Thanks everyone!

## Outreachy folks
Hi all :raising_hand: 
The Call for proposals on the PublicLab website is still ongoing [here](https://publiclab.org/notes/cess/04-04-2022/call-for-proposals-outreachy-summer-2022). Please post early so we can give feedback you could incorporate on your final submission on the Outreachy website.
We have had the most Outreachy interaction ever this round! I am still trying to get through all the comments [on the discussion/introduction issue](https://github.com/publiclab/plots2/issues/10840) :smiley: 
We are really glad to have you all here, and thanks for considering PublicLab for your internship :heart: :heart: 
I would really like to thank everyone for helping out each other and even the GSoC applicants once they came along. It has really helped the mentors and the co-ordinators: the information transfer and pointing each other in the right direction and even creating first-timer issues :tada: :tada: it is really good having all of you around. Thank you all for your contributions and patience :100: 
 Feel free to share what you are working on, and if we have missed a question kindly ask again below. Also if you are blocked on anything, please mention below and we will try to unblock you. Thanks all

 ## This week's focus Issues
I would like to urge everyone to remember to be kind to themselves this week and in the coming few weeks. Remember to take some rest if required. Please also do ask for help if you are stuck or feeling overwhelmed. 

### Thank you note to focus issues contributors
It would be a long list and easy to miss some folks if were to mention all the people who have helped, contributed, and interacted across all the platforms.
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 
 So thanks again everyone for helping out. We really appreciate all the help and contributions.
 :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by shubhangi013** [comment]
I come from a region where crop and plant health, in general, is of extreme importance and while contributing to Infragram, it felt very good because I could resonate with the underlying purpose and also interact with ever-patient and helpful @TildaDares @jywarren and @cesswairimu. 
I will soon submit my proposal for review and really look forward to contributing to Infragram!

**Comment by PeculiarE** [comment]
Thank you too @cesswairimu (and @jywarren and @TildaDares) for being patient and supportive ❤️ . I believe the collaboration  between we applicants is just a reflection of the Public Lab tradition and I, for one, am glad I chose this community to contribute to and be a part of.

This week, I am working on my proposal. and steadily reminding myself it doesn't have to be perfect before I submit it for review. I do have questions on some parts of the mapknitter spam project [which I have asked on the project discussion page](https://github.com/publiclab/plots2/issues/10754#issuecomment-1096705837). I would really appreciate it I could get answers to these questions to solidify my understanding of the project.

And if it's okay, I would like to open the next check-in @cesswairimu. Thank you 😄

**Comment by Somya-Singhal** [comment]
Thank you @TildaDares @jywarren @cesswairimu for constantly helping us out and giving us regular feedback. It is a great experience to keep working with such a welcoming community.
I am working on my proposal and would be submitting it soon for review and feedback and also looking ahead to solve more issues. I am eagerly looking ahead to contributing to infragram repository. 
Also interested to open next check-in!!Thank you all!!🙂🙂

**Comment by stephaniequintana** [comment]
I just wanted to drop a quick line to let everyone know how much I am enjoying (& appreciating) being a part of this community. 

This past week I was able to participate in my second weekly community call. These have been so great and informative! I met Senior Program Director, Stevie Klass, and the Kits Fulfillment Manager, Alahna Morre. As with everyone else I've met and worked with in the community, both were incredibly welcoming and helpful. Too, Alahna was able to share a great deal about Infragram overall as well as some of the constraints with obtaining kits, ideas about where the software is headed and community outreach initiatives under way. This, along with having had the opportunity (last week) to meet and chat with Liz Barry (Director of Community Development) and the overall mission and direction of Public Lab confirm that this is the type of community I want to be involved with. If you haven't yet, I highly recommend becoming more familiar with the community as a whole through [these calls](https://publiclab.org/events).


I also worked further on my proposal (Infragram Full Screen Design) - generally, identifying information in the wiki articles that I would like to provide more direct access to and, more specifically, creating a Bootstrap mockup of the site layouts. As such, I will continue to churn away, gather as much pertinent information available and continue familiarizing myself with all things Public Lab.

Hope everyone else had a great week, too, and that next week is even better!

**Comment by sarxxt** [comment]
Its my first time contributing in open source and I am really enjoying it. Thanks @jywarren @TildaDares for being so supportive.
I am working on infragram proposal and really looking forward to work on this project.

**Comment by PeculiarE** [comment]
Hi @cesswairimu, I've created the next check-in [here](https://github.com/publiclab/mapknitter/issues/1659) in advance for tomorrow. Could you please review and lemme know if there any changes I need to make? Thank you!!!!

**Comment by cesswairimu** [comment]
Hi @PeculiarE , I just saw it. Its looking good. Thanks

Moved to https://github.com/publiclab/mapknitter/issues/1659. Thanks all

**Comment by PeculiarE** [comment]
Thank you 😄  @cesswairimu

**Comment by cesswairimu** [comment]
sure thing, done. Thanks
