### ISSUE TITLE
table of contents bar to make navigation easier

### ISSUE THREAD

**Issue by shubhangi013** [publiclab/infragram#391]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file `https://github.com/publiclab/infragram/blob/main/README.md` in the `https://github.com/publiclab/infragram` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
If you get stuck, you can checkout my implementation of this idea here : https://github.com/shubhangi013/infragram/tree/toc#table-of-contents
Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff

+## Table of Contents
+
+1. [Quick Installation](#quick-installation)
+2. [Purpose](#purpose)
+3. [Usage](#usage)
+4. [Architecture](#architecture)
+5. [Inputs](#inputs)
+    - [File Upload](#file-upload)
+    - [Video](#video)
+6. [Converting](#converting)
+    - [Infragrammar](#infragrammar)
+7. [Processors](#processors)
+8. [Presets](#presets)
+9. [Colorizing](#colorizing)
+10. [Outputs](#outputs)
+    - [Export To Publiclab.org](#export-to-publiclaborg)
+    - [Export to Image Sequencer](#export-to-image-sequencer)
+11. [Interface](#interface)
+12. [Legacy Code](#legacy-code)
+13. [Pi and VR versions](#pi-and-vr-versions)
+14. [Contributing](#contributing)
+    - [Code of Conduct](#code-of-conduct)
+15. [Developers](#developers)
+16. [First Time?](#first-time)
+****


```
it is expected to look like this :
![Screenshot from 2022-04-20 13-23-25](https://user-images.githubusercontent.com/78342516/164179537-0867b742-6560-4f69-85d7-3416f782f87c.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Hi @shubhangi013, can you add indentation to the links? It'll be easier to know which headings are subheadings.

**Comment by shubhangi013** [comment]
> Hi @shubhangi013, can you add indentation to the links? It'll be easier to know which headings are subheadings.

Done! I've also updated the branch wherein one can find the adequately indented code if they get stuck.

**Comment by TildaDares** [comment]
Hi @shubhangi013, I just noticed something weird in the readme I'd like to change #394. After that, we can move ahead with this one but you'll have to make some changes.

**Comment by TildaDares** [comment]
Hi @shubhangi013, you can update your issue now.

**Comment by shubhangi013** [comment]
Hey @TildaDares ! I've done it. :smile:

**Comment by TildaDares** [comment]
Thanks @shubhangi013!!

**Comment by TildaDares** [comment]
Reserved for @Deepthi562

**Comment by Deepthi562** [comment]
Thanks, @TildaDares I'm working on it. I will get back to you as soon as possible.

**Comment by TildaDares** [comment]
Hi @Deepthi562, you pushed to your fork instead of `publiclab/plots2`.

**Comment by Deepthi562** [comment]
@TildaDares i am a beginner sorry about that, im checking it.

**Comment by Deepthi562** [comment]
@TildaDares I actually haven't done anything specifically to push into my fork. I made sure that the head repo is publiclab. Correct me if anything is wrong or changes to be made with the attached screenshot.
![pic18](https://user-images.githubusercontent.com/71760959/164707442-12a9e91c-7488-4138-a445-d1a70b27b819.png)
