### ISSUE TITLE
Weekly Community Check-In #139 - Perseverance 

### ISSUE THREAD

**Issue by on2onyekachi** [publiclab/infragram#406]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Perseverance 

We all thrive on being successful and in doing so we often forget the difficulties lying in the path to success. We set targets and want to achieve them right away, but we are humans and may fall short of those goals.

When a child learns to stand up and tries to walk, he is found to fall down again and again. And by nature and instinct, he gets up, and again tries to step forward, although again he falls down. But ultimately, he succeeds in walking. The same thing had once happened to each one of us as a toddler.

Similarly, in spite of repeated failures, a man having perseverance does not admit his defeat and failure. He tries again and again, and finally attains success. A persevering person is one who has tremendous self-confi­dence, determination, a natural urge towards hard labor, and untiring energy to continue till the last, without grumbling or expressing dissatisfaction.

Success, despite popular belief, isn’t a one-way path or a straight line. It is a muddled road with various ups and downs, and you should navigate it with care. You might fall or get lost on your way. However, if you keep going, you will eventually reach your destination.

### Thank you note to focus issues contributors

🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

What we learn with pleasure, we never forget. [asaayushisingh](https://github.com/asaayushisingh), @shefali12-ab,  @girija0707  @PeculiarE @akanbifatimah [RaviAnand111](https://github.com/RaviAnand111), and many others. Thank you all for bringing your expertise and experience around the table, everyone has really been supportive in one way or the other during the application periods.

Many thanks to our mentors and maintenance as well, @jywarren @cesswairimu @TildaDares [@dependabot[bot]](https://github.com/apps/dependabot),  for taking their time and effort to ensure maximum stability throughout the application period. 

🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by akanbifatimah** [comment]
Thank you @on2onyekachi for this thoughtful message, "Success, despite popular belief, isn’t a one-way path or a straight line. It is a muddled road with various ups and downs, and you should navigate it with care."...so true, thank you again.

**Comment by illyShelly** [comment]
@on2onyekachi this is awesome. I love it. The mud sometimes becomes even wetland 😅

**Comment by girija0707** [comment]
Beautifully written @on2onyekachi ♥️ This reminds me of a quote, 'things may seem colossal and we're small, yet if we persist', though I don't remember the exact words as this was from the chapters we had in school 😅 
Also thank you for the mention, it's always a fun and great learning experience to work with wonderful mentors and peers 😊

**Comment by SHIVANGISINGH1** [comment]
@on2onyekachi such an amazing thought 👍❤. Thank you so much for motivating us to keep working hard ✌

**Comment by PeculiarE** [comment]
Thank you @on2onyekachi 😄 ❤️. Your message is timely, encouraging, and very much appreciated 🎉 . Thank you for the mention, I had fun contributing and helping out (and being helped as well 😆 ). Truly, 'what we learn with pleasure, we never forget' 👍

**Comment by Somya-Singhal** [comment]
Thank you @on2onyekachi , for encouraging all of us through your amazing thought. You said it right that we should never stop and keep learning from our failures.

**Comment by jywarren** [comment]
> Success, despite popular belief, isn’t a one-way path or a straight line

So true, and thank you for this!!!

It's been a busy few weeks and thank you all so much for all the hard work that's gone into these weeks. We're very grateful for your time and perseverance!

**Comment by cesswairimu** [comment]
Hi @Somya-Singhal, sure thing, feel free to open one today or tomorrow. Thanks all

**Comment by Somya-Singhal** [comment]
Thank you @cesswairimu, for giving me this opportunity. I have opened weekly community check-in [here](https://github.com/publiclab/infragram/issues/409)

**Comment by cesswairimu** [comment]
Great :tada: , thanks @Somya-Singhal.  Moved to https://github.com/publiclab/infragram/issues/409.  Thanks all
