### ISSUE TITLE
Weekly Community Check-In #140 - Persistence and Patience

### ISSUE THREAD

**Issue by Somya-Singhal** [publiclab/infragram#409]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform that helps a newcomer to become a leader of tomorrow. 💯

## Persistence and Patience
These two words have great power in our lives. We all can remember instances where we accomplished something because we were persistent. The key factor that supplemented our persistence was patience. Patience to trust the process. Patience to wait for the result. There is a saying "Good things come to those who wait". Everyone in life who achieved success has to keep on working despite the difficultly or opposition and I believe that this is important for progress in our life. Sometimes it may take years to accomplish something that we want but the important thing is that we don't have to give up if we don't see results immediately. It may take time for the right things to enter into your life. But at last, what's yours, you will get.

We always should try to give our best and enjoy the whole process of learning. We should not rush for learning everything but instead try to learn even small in the best possible manner so that it would give inner satisfaction that whatever we have learned, we are knowing it well.

## Thank you note to focus issues contributors
🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

"All great achievements require time",@SHIVANGISINGH1 @on2onyekachi @mittal-parth @PeculiarE. Thank you to all the contributors for being supportive throughout the whole application period by helping everyone and encouraging each one of us.

A huge thanks to our mentors as well, @TildaDares @jywarren @cesswairimu [@dependabot[bot]](https://github.com/apps/dependabot), for constantly giving feedback to each one us and being patient. With your help and support the whole contribution period had been possible to be smooth and really enjoyable.

🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas https://github.com/publiclab/plots2/issues/9480. If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.

**Thanks everyone for making Public Lab awesome ❤️**
Have a great week ahead all 🎈

**Comment by SHIVANGISINGH1** [comment]
Very inspiring thought @Somya-Singhal ❤😊, I remember one great saying which fits in perfectly "All great achievements require time". If we believe in something we should not give up but try harder and someday we will see the result of our hard work. ✌

Thank you so much for sharing 🙇‍♀️❤

**Comment by Somya-Singhal** [comment]
Thank you @SHIVANGISINGH1😃😃

**Comment by PeculiarE** [comment]
Thank you @Somya-Singhal for sharing these pearls of wisdom ❤️ . Persistence and patience have paid off in more ways than one for me, especially during the past few days 😄 😄

**Comment by on2onyekachi** [comment]
Awesome!, Thanks @Somya-Singhal

**Comment by mittal-parth** [comment]
Beautifully written! Thank you @Somya-Singhal! ✨

**Comment by Somya-Singhal** [comment]
Thank you @on2onyekachi @mittal-parth @PeculiarE. I am glad that you all liked it.

**Comment by cesswairimu** [comment]
Hi all, great theme @Somya-Singhal, the two are really crucial esp in this career path,  thanks.
Would anyone like to open next week's check-in?

**Comment by shefali12-ab** [comment]
> Hi all, great theme @Somya-Singhal, the two are really crucial esp in this career path, thanks. Would anyone like to open next week's check-in?

Hey, @cesswairimu I would like to open next week's check-in.

**Comment by cesswairimu** [comment]
Awesome :tada: @shefali12-ab please feel free to open any time today, Thanks

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/11122. Thanks all
