### ISSUE TITLE
Weekly Community Check-In #142 : Teamwork

### ISSUE THREAD

**Issue by simransia** [publiclab/infragram#412]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

<h2>TEAMWORK👫🏻🧑🏻‍🤝‍🧑🏻👫🏻</h2>

The evolution of mankind has always depended on joining hands with each other. From ancient pyramids to spacecrafts, everything is possible only because of teamwork! This process goes on in parallel with time. The importance of teamwork could also be acknowledged by the quote:

### `⭐️"No one can whistle a symphony. It takes a whole orchestra to play it!"⭐️`

I had a great time working with the members of the Public labs during my contribution period. And I want to share three main important points about teamwork which I have realized and appreciate a lot as well.

<h3>1)  Learning: 👩‍💻</h3>

This is the main benefit of working in a team. Teamwork provided an opportunity to everyone by which everyone can learn so many new things from each other's experiences. It helps in developing the abilities and capabilities of the members and it fosters a learning environment which results in the overall growth of an individual.
<p  align="center">
<img height="200px" width="350px" src="https://user-images.githubusercontent.com/88017902/168728341-63ad7ce2-f530-4081-bd98-1ddadc431bb5.jpg" >
</p>

<h3 align="center">

> ⭐️"I can do things you cannot, you can do things I cannot: together we can do great things."⭐️

</h3>

#

<h3>2) New ideas: 💫</h3>

When there is a problem to be solved, then all the team members come up with their own ideas so, there are many ways open up to solve a single problem and out of which the best option can be selected. And in some cases, all the ideas can combine to provide a more better result. 

<p  align="center">
<img height="200px" width="350px" src="https://user-images.githubusercontent.com/88017902/168728431-1cc3d705-c106-4b41-91c5-664ea199d8e2.jpg">
</p>
<h3  align="center">

> ⭐️" None of us is as smart as all of us! "⭐️

</h3>

#
<h3>3) Bonding: 🤝</h3>

This is the best thing that happens when people work collaboratively. Working in a team, a positive environment is created by which all the team members are able to work well. Whenever someone is stuck on any problem, every other team member is always standing there to provide the help that they could. It builds up a strong relationship and bonding among team members.

<p  align="center">
<img height="200px" width="350px" src="https://user-images.githubusercontent.com/88017902/168728441-b1dabff7-419c-4ea2-8bd8-2ad1c3f25c46.jpg">
</p>

<h3  align="center">

> ⭐️" When 'I' is replaced by "we" even 'illness' becomes 'wellness'. "⭐️

</h3>

# 

I am sure you all also had a great experience of working in a team and collaborating with the members of Public Labs. Please share your experience with others in the comments below. You can express your gratitude for all the help you get and you could also express your own thoughts on "Teamwork".

<h3>Thank you note: ❤️</h3>
A big thankyou to all the contributors who have contributed to public lab and the mentors @jywarren @TildaDares @cesswairimu for there constant support and guidance! Also, I would like to especially thank @akanbifatimah , @stephaniequintana, @kunmi02, @PeculiarE, and many other nice people for all the guidance and support. 💛 

<h2>Next Check-in ✍🏼 </h2>
If you would like to open the next check-in. Leave a comment below. We are happy to help if its your first time.🎉 

<h3>Check-in Ideas</h3>

We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480) . If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.

Thanks everyone for making Public Lab awesome ❤️
Have a great week ahead all 🎈

**Comment by on2onyekachi** [comment]
@simransia  Thank you for this. 

Really, engaging in teamwork activities helps to overcome doubts and insecurities about working with others. The understanding I have gained while working with others has provided me with increased confidence and inclination to undertake teamwork in my future career, allowing me to attain the benefits of teamwork in it.

**Comment by simransia** [comment]
You're very welcome @on2onyekachi, and yes teamwork teaches us a lot!
It's my pleasure @akanbifatimah , thank you  for the appreciation!

**Comment by kunmi02** [comment]
Thank you @simransia. I am glad our path crossed during this phase.
This contribution period actually made me fall in love with open source and I am already thinking of following this path. I love the collaborative and bonding part cause I actually made a new friend.... shout to @akanbifatimah  🥳 🎉 🥂 🍾 🎊 .. Great lady on and off the screen... Hoping to connect with the other guys outside the community. 
OpenSource should make welcome a new king cos I am coming ✈️ .... PublicLab will definitely be seeing more of me going forward.

**Comment by PeculiarE** [comment]
Thank you @simransia for this very important message and the mention ❤️ 

During and even after the contribution period, I did indeed reap the benefits of teamwork. Seeking clarifications and also offering help to fellow contributors helped hasten my understanding of the Ruby language and the projects in general, gave me ideas on how to fix a problem, and helped me make new friends 🥳 🥳 

I personally love all the little quotes in your message. They help to beautifully capture the spirit and essence of teamwork in just a few words.

Teamwork is reflected in all areas of life, even in soccer (one of my favourite sports of all time 😄 ). No matter how many talented players are in a team, if they can't work together, that team won't win any trophies.

To wrap up, I am immensely grateful to everyone (mentors, members, and fellow contributors) who answered all my questions, provided helpful pointers, and encouraged me one way or the other. Y'all made my introduction to open source way more interesting and rewarding than I expected. Thank you ❤️ ❤️

**Comment by SHIVANGISINGH1** [comment]
A very inspiring message on teamwork @simransia 😊👌

While contributing to open source, I have realized the importance of teamwork even more🙇‍♀️ 
Working with very helpful, kind, and supportive people is what makes open-source unique 😎💖. I can say that I have felt the strength of teamwork here so much more than at any other places I have worked before because at times I have felt left out in teams and the team members not being supportive at all 😔💔

But in an open-source community, we can see what good teamwork can do and how much important it is!

Thank you so much for sharing ☺️☺️❤️

**Comment by RaviAnand111** [comment]
Very good topic @simransia, I agree with you totally, working in a team teaches you alot, conversation, how to move across ideas, etc.  I have learned alot in this community because of caring and supportive people here.

**Comment by simransia** [comment]
Thankyou so much❤️ @kunmi02 , @Ishhha ,@PeculiarE, @illyShelly , @SHIVANGISINGH1 and @RaviAnand111 for sharing your own experiences and thoughts about teamwork. It was so good to read all of your comments! Also thanks for all the appreciation you gave to this community check-in message.😊 
Let's stay together and rise together! 🌈🤜🤛✨ 

Cheers!!😍

**Comment by cesswairimu** [comment]
Hi all and great check-in @simransia :heart: , thanks. I agree with everyone :100:  : I learn a lot from this community each week  and the teamwork and collaboration is so powerful.
Hi @Ishhha awesome :tada:,  you can find the template that we use to create [here](https://github.com/publiclab/plots2/issues/new/choose)(select the **Weekly Check-in** one ). You can open on Sunday evening or anytime Monday.  Feel free to ping me or ask here if you need any help. Thanks

**Comment by cesswairimu** [comment]
Hi @Ishhha , please feel free to open the check-in anytime today or let us know if you need any help. Thanks

**Comment by jywarren** [comment]
Thank you so much for this check-in theme @simransia -- also agreed 💯 !!!! ⭐ ⭐ ⭐

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/PublicLab.Editor/issues/863. Thanks all
