### ISSUE TITLE
Weekly Community Check-In #148 - Coding Playlist

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/infragram#433]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Coding Playlist

Last year we had this topic and  people shared  some great playlists you can check them [here](https://github.com/publiclab/plots2/issues/10154).  This week lets share playlists we love listening to when coding. If you do not listen to music while coding; feel free to share any other thing you do, could be even a beverage you normally take. 

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

- https://github.com/publiclab/plots2/issues/11123

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to contributors of the past few weeks

:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal::1st_place_medal:
@Kshitiz-Mhto, @thexjoker71, @jindalj, @AbhayK200417, @noleni, @abhiramshukla, @bad-atnames0, @leighbriody, @XD69Z, @udyanojha, @gunesnt, @KarishmaVanwari, @gitofbabai, @anirudhprabhakaran3, @jywarren, @preeti-14-7, @pokacyb, @jenniferhalloran, @RafiyaZafar
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal::1st_place_medal:

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
I listen [to this  a lot when coding](https://www.youtube.com/watch?v=Nllc4nwJZk8) It also have beautiful sceneries that I sometime watch on breaks.

Lets keep this check-in for another week. Thanks all

**Comment by cesswairimu** [comment]
MOved to https://github.com/publiclab/plots2/issues/11315. Thanks all

**Comment by PeculiarE** [comment]
I know I'm a bit late to the party on this one but I just wanted to say that I love listening to music and coding, but only as two separate endeavours 😆 😆

I can never seem to effectively do both at the same time. Probably because I'm more of a rap and hip-hop gal, and so most times I find myself singing and dancing to the songs rather than actually coding 🤣

But a must-have when I'm coding is a bottle of water to stay hydrated and help me glance away from the screen from time to time.

**Comment by udyanojha** [comment]
> 

I agree I used to play Snoop while doing DSA questions. Not suggested while coding 😂. 
Then switched to no music mode it was effective. 
Today after being stuck for too long, I switched genre to low-fi something, and it did the trick, head nodding and problem-solving. 
Sometimes I take a brisk walk to clear my mind and let my subconscious do the job.

**Comment by jywarren** [comment]
So true, lyrics especially are tough to have as background!!!
