### ISSUE TITLE
Discuss write test on new Infragram UI

### ISSUE THREAD

**Issue by Forchapeatl** [publiclab/infragram#448]
>Write UI tests for new Infragram UI, using Jest (https://jestjs.io/)

Hello @jywarren . I needed your consultatation on a few request.

1. I have gained familiarity with the [src/ui](https://github.com/publiclab/infragram/tree/main/src/ui) directory, as a result I wish to plead that during this period I conduct jestjs on the files of that directory as I don't fully understand how to stimulate file uploads and camera feeds as per the [src/io](https://github.com/publiclab/infragram/tree/main/src/io) where most of the events are dealing with media data upload / download. The [src/processors](https://github.com/publiclab/infragram/tree/main/src/processors) returns  mathematical values and I still haven't been able to get Jestjs stimulate `Canvas` pixels. same  goes with the [src/util](https://github.com/publiclab/infragram/tree/main/src/util) folder.
2.  In  summary. I wish to plead that during this internship period I conduct Jestjs test on the [src/ui](https://github.com/publiclab/infragram/tree/main/src/ui) folder as there are available resources on manipulating DOM element on jstest. If you don't mind.

**Comment by jywarren** [comment]
Yes, i think testing the UI sounds great -- it's actually far more prone to
bugs and errors anyways. There are ways to simulate uploads and canvas, but
it's quite complex. You can see some of this at
https://github.com/publiclab/image-sequencer if you're interested, but it's
a lot of work to do!

**Comment by Forchapeatl** [comment]
Thank you
