### ISSUE TITLE
Failed to execute 'getAttribLocation' error in local machine

### ISSUE THREAD

**Issue by avsingh999** [publiclab/infragram#48]
When I was opening https://github.com/publiclab/infragram/blob/main/index.html this file in my browser and inspect this page, then this showing this error
![infa2](https://user-images.githubusercontent.com/25536022/51076879-7db62180-16c4-11e9-8058-03df9ab373a0.gif)

**Comment by jywarren** [comment]
Agreed!

**Comment by gauravano** [comment]
Let's close this one then :sweat_smile:. Thanks all!
