### ISSUE TITLE
Add Code_of_conduct to this repository

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/infragram#49]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/infragram/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Create** the file named [CODE_OF_CONDUCT.md] in the `infragram` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

The file needs to be created at the root of the repository and copy the code of conduct from https://github.com/publiclab/plots2/blob/master/CODE_OF_CONDUCT.md

into newly created file. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by RizwanSyed357** [comment]
Hi, I'd like to work on this issue please, if no one else is? I have never contributed to open source and think this would an amazing place to start :-)

**Comment by gauravano** [comment]
Welcome to Public Lab @RizwanSyed357! We will try to make your first Open Source contribution as awesome as possible. Thanks!

**Comment by RizwanSyed357** [comment]
Cheers @gauravano , I appreciate it :)

**Comment by govindgoel** [comment]
@gauravano  Code of conduct is still not added should i make a PR and close this issue.

**Comment by reapedjuggler** [comment]
Can I work on this issue?

**Comment by grvsachdeva** [comment]
Hi @govindgoel, sorry for missing your comment. I see you have already solved some issues at Public Lab so @reapedjuggler can take this one as their first-time contribution. Normally, we welcome collaboration on solving issues but this one is a small one 😄. 

@reapedjuggler there is a PR already open for solving this issue - https://github.com/publiclab/infragram/pull/53 though that need more changes as the final format for code of conduct is https://github.com/publiclab/plots2/pull/5362/files

Can you push commits to the existing PR?

Thank you, everyone!

**Comment by reapedjuggler** [comment]
Thank you @grvsachdeva for assigning me this issue, Looking forward to contribute more in@publiclab :smiley:

**Comment by reapedjuggler** [comment]
@grvsachdeva about the later point

> Can you push commits to the existing PR?

Can it be solved by this [https://stackoverflow.com/questions/33902158/is-it-possible-to-continue-a-pull-request-opened-by-someone-else-on-github#:~:text=2%20Answers&text=The%20only%20way%20to%20update,amend%20the%20PR%2C%20by%20default.](url) 

Or am I missing something over here ??
Thank you for your guidance :)

**Comment by grvsachdeva** [comment]
You can pull the @RS357 's PR branch, make commits and try to push the commits and that should reflect on the existing PR. There is a possibility that you may not able to push on @RS357 's branch but check once.

**Comment by reapedjuggler** [comment]
@grvsachdeva setting up the remote to @RS357 repo worked I have continued the PR of the same :smiley:

**Comment by grvsachdeva** [comment]
Saw the PR. Good job 👍 . Please close your PR, and let's get #148 to merging. Thanks!

**Comment by grvsachdeva** [comment]
Oops, just saw that Infragram readme has a Code of conduct section point to the website, in which case, I believe we don't want this anymore. @jywarren @cesswairimu please confirm regarding the same. Thanks!

**Comment by cesswairimu** [comment]
Oh yeah I see...I think it may be nice to have it as a file too and it shouldn't contradict since they both point to the same place...not so sure about this @jywarren @RuthNjeri  what do you think?
