### ISSUE TITLE
Open link new Tab

### ISSUE THREAD

**Issue by avsingh999** [publiclab/infragram#8]
In this page there are some link's but they are only open same page it must be open new tab 

https://github.com/publiclab/infragram/blob/eb9fc19f993616caf9aa0311f7468d33c4529253/index.html#L93

https://github.com/publiclab/infragram/blob/eb9fc19f993616caf9aa0311f7468d33c4529253/index.html#L208

https://github.com/publiclab/infragram/blob/eb9fc19f993616caf9aa0311f7468d33c4529253/index.html#L209

**Comment by avsingh999** [comment]
@jywarren  If it's valid please add label

**Comment by vikul1234** [comment]
@jywarren @avsingh999 can i work on this issue?

**Comment by jywarren** [comment]
Sure, go ahead!
