### ISSUE TITLE
Begin now and Get help & learn more buttons are collapse 

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/infragram#82]
### Please describe the problem (or idea)
Begin now and Get help & learn more buttons are collapse to each other and also not responsive 
> What happened just before the problem occurred? Or what problem could this idea solve?
### Screenshot 1
![collapse3](https://user-images.githubusercontent.com/25260367/46573000-a08db700-c9ac-11e8-9661-4472acb7bb93.PNG)
### Screenshot 2
![collapse2](https://user-images.githubusercontent.com/25260367/46573002-a71c2e80-c9ac-11e8-9dc3-1534d9038e66.PNG)
### Screenshot 3
![collapse1](https://user-images.githubusercontent.com/25260367/46573003-aa171f00-c9ac-11e8-9fd8-ac5faf245710.PNG)

> What did you expect to see that you didn't?

### Please show us where to look
https://infragram.org
### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Let's keep it here in infragram. Anyone who wants to solve this one, please leave a comment below and go ahead. Thanks!! 

Thanks @DakshGondaliya for updating.

**Comment by pydevsg** [comment]
I would like to work on this @DakshGondaliya , @gauravano .
Can I work on this?

**Comment by pydevsg** [comment]
@DakshGondaliya I went through this and I think this issue is fixed now.
![_20191111_130222](https://user-images.githubusercontent.com/40278255/68569401-fff9a880-0483-11ea-857a-6f50ed9e07b4.jpg)

**Comment by JosueKinda** [comment]
I will like to work on this

**Comment by tatiPFernandes** [comment]
Hi, does this issue still need to be worked on?

**Comment by abhaygzb15** [comment]
@DakshGondaliya Please assign this issue to me

**Comment by DakshGondaliya** [comment]
Closing this issue as it is working fine now.
