### ISSUE TITLE
Add Installation in README file

### ISSUE THREAD

**Issue by pydevsg** [publiclab/infragram#86]
The current README file doesn't have a procedure for Installation of this project to run it locally.An installation setup should be written for helping the beginners run it locally.

**Comment by pydevsg** [comment]
cc @jywarren 
I would like to work on this.

**Comment by jywarren** [comment]
That would be super!

**Comment by pydevsg** [comment]
You can see my PR - #88 which have resolved the same.
Thanks @jywarren .
