### ISSUE TITLE
Upload an image button not working

### ISSUE THREAD

**Issue by pydevsg** [publiclab/infragram#87]
I ran  https://publiclab.github.io/infragram/ and was trying to see the working on this project by uploading an image in the `upload an image` button. But on clicking the button it isn't working.
I am using Google Chrome Browser and tried this on Opera as well but it seemed not to be working.

![Infragram_upload_button](https://user-images.githubusercontent.com/40278255/68572988-c4171100-048c-11ea-953b-1e4b85fd266c.png)

**Comment by pydevsg** [comment]
@jywarren  what do you think ?

**Comment by jywarren** [comment]
Ah sorry for slow response -- I think you're right, and we should fix this
-- i think currently it may only work if you drag an image onto it? Let's
try to highlight the section of code that's responsible for this!

**Comment by pydevsg** [comment]
Okay will try to find out the code and refer here. Thanks for your response.

**Comment by govindgoel** [comment]
@pydevsg  Hi There I tried to found out the code for this issue and I have refrenced it here.
The link to the file: |https://github.com/publiclab/infragram/blob/main/index.html#L87-L98|
I will try my best If I would be able to help in this.
Happy Coding!

**Comment by jywarren** [comment]
Oh, that would be great! We'd love a fix for this. Thank you!

**Comment by govindgoel** [comment]
@pydevsg @jywarren I found out that by changing the data toggle attribute value to "buttons" ,The upload a image button is working,Can you please help me out in these.

**Comment by pydevsg** [comment]
Yeah @govindgoel . Please make a commit from your local branch and make a PR so that we can review and fix the bug. If you need any help feel free to ask :)

**Comment by govindgoel** [comment]
@pydevsg  I have done that,thanks for the guidance.

**Comment by jywarren** [comment]
Can you link us to your PR from here? Thank you! This is a critical fix!!!

**Comment by jywarren** [comment]
OH hm, I wasn't able to confirm that this worked in Chrome on a mac - it still doesn't open. I'm going to re-open, can others try this out? It's live at https://infragram.org/sandbox right now.

**Comment by pydevsg** [comment]
@jywarren I would like to guve it a try.

**Comment by jywarren** [comment]
please do! Thank you!

**Comment by Ole2rup** [comment]
This problem still exists, it's quite annoying.

**Comment by publiclab-mimi** [comment]
Can confirm that this problem still exists. Unable to drag and drop an image or upload from Safari or Chrome.

**Comment by jywarren** [comment]
Hi all, I was able to upload on Mac OS Safari/Chrome by dragging an image onto the Upload button as shown here:

![image](https://user-images.githubusercontent.com/24359/76866747-f4a3f880-683a-11ea-9906-3ec505354127.png)

There is still definitely a bug in image selection but this particular workaround seemed to work for me. Is this not precisely what you're seeing? Thanks for helping to debug.

**Comment by jywarren** [comment]
Awesome. I think i fixed this. Can folks test it out at https://publiclab.github.io/infragram/

And if it works we'll publish this to infragram.org/sandbox too.

**Comment by jywarren** [comment]
confirmed on Safari

**Comment by jywarren** [comment]
This is now live on https://infragram.org/sandbox/ -- I'm going to close this! You should now be able to click the upload file button and select a file in the OS dialogue. 

Thank you, and if you find other instances or variants or just new bugs, please be in touch!
