### ISSUE TITLE
Upload image button is not working 

### ISSUE THREAD

**Issue by blyatruski** [publiclab/infragram#96]
after the latest update on https://infragram.org/sandbox/ the "UPLOAD IMAGE " button has stopeed working .... it used to work fine bfore this update ... 
<img width="1230" alt="Screenshot 2020-01-13 at 3 06 34 PM" src="https://user-images.githubusercontent.com/56097019/72245359-65018400-3616-11ea-81be-507cb11cad9a.png">

PLS FIX

**Comment by jywarren** [comment]
Hi, if you drag your image onto the button it will work. We are working on
a broader fix for this as well, thank you for reporting.

**Comment by jywarren** [comment]
Hi! I believe we've fixed this in https://github.com/publiclab/infragram/pull/95 -- thank you, we'll publish it shortly!

**Comment by jywarren** [comment]
Can you confirm once we do? Thanks!

**Comment by jywarren** [comment]
Actually i'm not sure that fixed it - we are tracking it over here - can you leave feedback there to help us narrow in on this? Thank you!

https://github.com/publiclab/infragram/issues/87
